### ISSUE TITLE
"Paper" & "total" layering is not the same across screens

### ISSUE THREAD

**Issue by phet-steele** [phetsims/make-a-ten#266]
@amanda-phet the layering of the paper on the first screen puts it above the total:
<img width="337" alt="screen shot 2017-02-01 at 10 43 18 am" src="https://cloud.githubusercontent.com/assets/5863899/22518819/4ca45406-e86b-11e6-8a6d-ae550e700b11.png">

The layering on the 2nd and 3rd screens puts the paper under the total:
<img width="417" alt="screen shot 2017-02-01 at 10 43 27 am" src="https://cloud.githubusercontent.com/assets/5863899/22518824/5181657c-e86b-11e6-9050-7b26ec276a0a.png">

Should these be consistent? Which is preferred?

For phetsims/tasks/issues/767.

**Comment by amanda-phet** [comment]
Hm, I agree that these should be consistent, but I recall @bethstade having reasons for them layering differently. I would lean toward laying the paper over the text in all screens (including the game screen).

**Comment by bethstade** [comment]
I agree. Looks like paper should go on top.
Just a reminder, I am out to the country and email will be inconsistent until after Feb. 14th.

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/make-a-ten <make-a-ten@noreply.github.com>Cc: bethstade <stadee@colorado.edu>, Mention <mention@noreply.github.com>Sent: Wed, 01 Feb 2017 18:18:18 -0000 (UTC)Subject: Re: [phetsims/make-a-ten] "Paper" & "total" layering is not the same across screens (#266)

Hm, I agree that these should be consistent, but I recall @bethstade having reasons for them layering differently. I would lean toward laying the paper over the text in all screens (including the game screen).
&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by amanda-phet** [comment]
Let's change the logic then, so that paper is layered above text. Thanks for commenting from London, @bethstade !

**Comment by jonathanolson** [comment]
@amanda-phet, how should it layer with the other things (edit buttons and keypad on the adding screen, "next" button on the game)?

**Comment by amanda-phet** [comment]
Keypad should be on top (always). 
Numbers should be on top of edit, reset all, and next buttons.

**Comment by jonathanolson** [comment]
Made the requested changes. Also the numbers were over "Hide Total" in the first screen (which seemed inconsistent), so I moved that behind the numbers also.

Can you review?

**Comment by amanda-phet** [comment]
Looks good on the first two screens, but to be consistent the paper numbers should be layered over the text numbers and next button on the game screen.

**Comment by jonathanolson** [comment]
Sorry about that, definitely forgot about the formula on the game screen. Should be fixed.

**Comment by amanda-phet** [comment]
It is working for the formula, but still not the next button.

![screen shot 2017-02-03 at 12 11 57 pm](https://cloud.githubusercontent.com/assets/7852916/22604696/01596b44-ea0a-11e6-9950-571d7ee05890.png)
![screen shot 2017-02-03 at 12 12 03 pm](https://cloud.githubusercontent.com/assets/7852916/22604699/04bb6e4a-ea0a-11e6-9e71-feb596fb071a.png)

I think we decided it would layer over any button (edit, reset all, and next).

**Comment by jonathanolson** [comment]
Ok, should be fixed.

**Comment by amanda-phet** [comment]
Looks great, thanks.
